### ISSUE TITLE
Code producing compiler warning

### ISSUE THREAD

**Issue by Pharap** [yinkou/Arduboy-TinyFont#13]
This line is generating a warning:
https://github.com/yinkou/Arduboy-TinyFont/blob/edd726d755bddc1e57dcf2d74882896341373a84/src/Tinyfont.cpp#L51

> warning: comparison is always false due to limited range of data type [-Wtype-limits]

I didn't make a PR because I'm not sure what the best solution is because I don't know what the valid range for `c` is.
At a guess I would think that `255` should actually be `127`, but I'm not sure.

**Comment by BotiKis** [comment]
You are right, it is supposed to be 127.
I remember changing it to allow the use of the remaining 128 glyphs when there is a custom font but I don't believe it's necessary. If you do a PR I'll merge it.

While looking into the code I've also noticed that there is a double check on '\n' and a ton of c type casting... oh my oh my.

**Comment by Pharap** [comment]
You could introduce some variables that define the upper and lower bounds so people can change the values when adding custom glyphs.
E.g. `if ((static_cast<uint8_t>(c) < minimumCharacter) || (static_cast<uint8_t>(c) > maximumCharacter))`.

For now I've just made the minimal fix though.

---

> I've also noticed that there is a double check on '\n'

Indeed there is, I may as well throw together another PR to solve that since I have a few moments and it's an easy fix.

> and a ton of c type casting...

Some of which isn't strictly necessary.
E.g.
* `c = (char)127` 
* `uint8_t col = (uint8_t)x % sWidth;`, 
* `uint8_t d = (uint8_t)y%8;`

The type of the variable on the left hand side of the `=` forces the type to be narrowed, and the use of `%` will force a promotion to `int` anyway\*.

---

\* From [cppreference - Numeric promitions](https://en.cppreference.com/w/cpp/language/implicit_conversion#Numeric_promotions)
> arithmetic operators do not accept types smaller than `int` as arguments, and integral promotions are automatically applied after lvalue-to-rvalue conversion, if applicable

...
> `unsigned char`, `char8_t` (since C++20) or `unsigned short` can be converted to `int` if it can hold its entire value range, and `unsigned int` otherwise;
