### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by Pharap** [yinkou/Arduboy-TinyFont#18]
If you have the time, could you make a new release that includes all the latest changes?

(v3.2 is currently 14 commits behind, which is quite a lot of changes.)

**Comment by BotiKis** [comment]
Thanks for the info. Done.

**Comment by Pharap** [comment]
Thanks Boti.

Unfortunately, the version number in `library.properties` and `library.json` weren't incremented, so I've quickly made a PR for that (#19).
