### ISSUE TITLE
Two clashes and a possible resolution

### ISSUE THREAD

**Issue by ghost** [yinkou/Arduboy-TinyFont#4]
Hey, I was poking around your font (great work BTW) and I noticed that there are two clashes, 2 = Z, and 5 = S. I resolved this by the following two changes, 2:7F8F, and S:F87F and leaving Z and 5 as they where.  Where the numbers are the byte pattern with a nibble per row.

I don't really know how github works BTW, so I hope posting here is acceptable. Hope this is useful to you. :)

**Comment by BotiKis** [comment]
Hi there,

Thanks for your hint. Yeah you are right i should change this. I don't think i should change `'Z'` but rather` '2'` to look more like the rest of the font. Going to look into this on the weekend. ✌️

**Comment by epbarger** [comment]
Any update on this? I'm using this for [a project](https://github.com/epbarger/tinypicross), and would love to the see the `2` tweaked.

Great project!

**Comment by BotiKis** [comment]
Sorry, totally fell below my radar!
Updated :)
