### ISSUE TITLE
Wanted to say thank you.

### ISSUE THREAD

**Issue by amirrajan** [yinkou/Arduboy-TinyFont#6]
Not an issue, but wasn't sure how else to reach out to you. I'm using this library in my port of A Dark Room to Arduboy. It's a fantastic font :-)

I'd like to have a thank you to you in the credits. Anything you'd like me to put in there?

**Comment by BotiKis** [comment]
Thank you <3
It's great to hear that someone is using it in a game!
You can better reach me in the arduboy forums, my username is botisaurus. ;)

Nah you don't need to put anything there! Save progmem for the actual game haha ;D.
